### ISSUE TITLE
Hardcoded language code

### ISSUE THREAD

**Issue by Paulsky** [aleksandar-babic/magento2-GCR#1]
Hello,

First of all, thank you for this great plug-in!

I'm wondering if it's possible to make this part variable (in `/Airslamit/Gcr/view/frontend/templates/order/success.phtml`):

```
<!-- BEGIN GCR Language Code -->
<script>
  window.___gcfg = {
    lang: 'en_US'
  };
</script>
<!-- END GCR Language Code -->
```

Maybe it could be based on the store language? Because we are using a Magento website with multiple store views with different languages. Thank you in advance!

**Comment by aleksandar-babic** [comment]
Resolved in #2
